### ISSUE TITLE
Will this image be updated to newer RocketChat releases? 

### ISSUE THREAD

**Issue by rubydotexe** [RocketChat/Rocket.Chat.Embedded.arm64#10]
Hi! I was curious and wanted to know if there was any plans to update this build to a newer release of RocketChat? 

I've tried to edit the dockerfile myself a couple of times to see if I could get newer releases to work, but the build always fails because of fibers.js. 

For instance, if I try to upgrade to [release 4.6.4](https://github.com/RocketChat/Rocket.Chat/releases/tag/4.6.4) I'll always get this error even if I change the version of the node builder to correspond to the release notes. 

```
bundle/programs/server/npm/node_modules/immediate/dist/immediate.js
bundle/programs/server/npm/node_modules/immediate/dist/immediate.min.js
bundle/programs/server/npm/node_modules/immediate/README.md
bundle/star.json
bundle/server/
bundle/server/.bundle_version.txt
bundle/.node_version.txt
Removing intermediate container 1a0546281cf3
 ---> d2ce7d419bed
Step 14/25 : ADD . /app
 ---> a3efe6191bb0
Step 15/25 : RUN set -x  && cd /app/bundle/programs/server  && npm install  && rm -rf npm/node_modules/sharp  && npm install sharp@0.22.1  && mv node_modules/sharp npm/node_modules/sharp  && cd npm  && npm rebuild bcrypt --build-from-source  && npm cache clear --force
 ---> Running in 660d7276a123
+ cd /app/bundle/programs/server
+ npm install
npm WARN deprecated node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

> fibers@5.0.1 install /app/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

make: Entering directory '/app/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
In file included from /usr/include/ucontext.h:26:0,
                 from ../src/libcoro/coro.h:323,
                 from ../src/libcoro/coro.c:41:
/usr/include/aarch64-linux-gnu/sys/ucontext.h:51:5: error: unknown type name 'stack_t'
     stack_t uc_stack;
     ^~~~~~~
../src/libcoro/coro.c: In function 'coro_create':
../src/libcoro/coro.c:383:19: error: request for member 'ss_sp' in something not a structure or union
   ctx->uc.uc_stack.ss_sp    = sptr;
                   ^
../src/libcoro/coro.c:384:19: error: request for member 'ss_size' in something not a structure or union
   ctx->uc.uc_stack.ss_size  = (size_t)ssize;
                   ^
../src/libcoro/coro.c:385:19: error: request for member 'ss_flags' in something not a structure or union
   ctx->uc.uc_stack.ss_flags = 0;
                   ^
make: *** [Release/obj.target/fibers/src/libcoro/coro.o] Error 1
fibers.target.mk:123: recipe for target 'Release/obj.target/fibers/src/libcoro/coro.o' failed
make: Leaving directory '/app/bundle/programs/server/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 5.13.0-1030-oracle
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /app/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v14.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
make: Entering directory '/app/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
In file included from /usr/include/ucontext.h:26:0,
                 from ../src/libcoro/coro.h:323,
                 from ../src/libcoro/coro.c:41:
/usr/include/aarch64-linux-gnu/sys/ucontext.h:51:5: error: unknown type name 'stack_t'
     stack_t uc_stack;
     ^~~~~~~
../src/libcoro/coro.c: In function 'coro_create':
../src/libcoro/coro.c:383:19: error: request for member 'ss_sp' in something not a structure or union
   ctx->uc.uc_stack.ss_sp    = sptr;
                   ^
../src/libcoro/coro.c:384:19: error: request for member 'ss_size' in something not a structure or union
   ctx->uc.uc_stack.ss_size  = (size_t)ssize;
                   ^
../src/libcoro/coro.c:385:19: error: request for member 'ss_flags' in something not a structure or union
   ctx->uc.uc_stack.ss_flags = 0;
                   ^
make: *** [Release/obj.target/fibers/src/libcoro/coro.o] Error 1
fibers.target.mk:123: recipe for target 'Release/obj.target/fibers/src/libcoro/coro.o' failed
make: Leaving directory '/app/bundle/programs/server/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 5.13.0-1030-oracle
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /app/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v14.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@5.0.1 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@5.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-29T16_25_02_739Z-debug.log
1 error occurred:
        * Status: The command '/bin/sh -c set -x  && cd /app/bundle/programs/server  && npm install  && rm -rf npm/node_modules/sharp  && npm install sharp@0.22.1  && mv node_modules/sharp npm/node_modules/sharp  && cd npm  && npm rebuild bcrypt --build-from-source  && npm cache clear --force' returned a non-zero code: 1, Code: 1
 ```

**Comment by rubydotexe** [comment]
@Sing-Li Hi, sorry to tag you specifically, but I noticed you did the latest commit. I was wondering if you or anyone you might know specifically might have a response to this?

**Comment by tiger154** [comment]
I'm with @rubydotexe we really hope to be fixed this issue ASAP! 

I got the same error above when I tried to update the recent version of Rocketchat (6.1.3) 

When I installed it without changing it along with the document and the current version at ENV part is 4.1.2 which is 2 years old. 
After I installed I got the message below and I can see Mongo also needs to update. 

As security is also important! 

So, please help out @Sing-Li 

`+----------------------------------------------+
|                SERVER RUNNING                |
+----------------------------------------------+
 Rocket.Chat Version: 4.1.2
 NodeJS Version: 12.22.1 - arm64
 MongoDB Version: 4.0.12 
...

+----------------------------------------------------------------------+
|                              DEPRECATION                             |
+----------------------------------------------------------------------+
 YOUR CURRENT MONGODB VERSION (4.0.12) IS DEPRECATED
 IT WILL NOT BE SUPPORTED ON ROCKET.CHAT VERSION 5.0.0 AND GREATER,
 PLEASE UPGRADE MONGODB TO VERSION 4.2 OR GREATER  
...
`

**Comment by debdutdeb** [comment]
Hey folks - a quick update https://open.rocket.chat/channel/ubuntu-snap?msg=sWdsGp5AH3Jsd3bY8

**Comment by tiger154** [comment]
Thanks for the update! So If you work on that when would it be the date we can see ? just rough days info would be also good ! 
I'm counting on that day!
